[project]
name = "goldenshell"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.7"
dependencies = [
    "boto3>=1.28.0",
    "click>=8.1.0",
    "python-terraform>=0.10.1",
    "pyyaml>=6.0.0",
]
